### ISSUE TITLE
Vermijd CSS toe te voegen in JS, werk met een CSS classlist toggle bijvoorbeeld

### ISSUE THREAD

**Issue by solideagency** [RalphKocken/fix-the-flow-interactive-website#2]
https://github.com/RalphKocken/fix-the-flow-interactive-website/blob/dc5cd4131d8eb5e6c9ee47806fbf71c8951837ba/script.js#L39

**Comment by RalphKocken** [comment]
Opgelost door classes te maken met display: none of visibility: hidden
