### ISSUE TITLE
Probeer de structuur van Justus aan te houden (zie: https://github.com/ju5tu5/99boards/blob/main/assets/script/main.js)

### ISSUE THREAD

**Issue by solideagency** [RalphKocken/fix-the-flow-interactive-website#3]
1. Variabelen
2. Eventlisteners
3. Functies

https://github.com/RalphKocken/fix-the-flow-interactive-website/blob/dc5cd4131d8eb5e6c9ee47806fbf71c8951837ba/script.js#L64

**Comment by RalphKocken** [comment]
Structuur veranderd, is inderdaad overzichtelijker zo.
